### ISSUE TITLE
Make Azure v2 alpha API docs available

### ISSUE THREAD

**Issue by mnlumi** [pulumi/registry#2569]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

For the ongoing development of Azure v2, it would be highly useful to have the alpha/pre-release API docs available for users while they are testing and providing feedback. The current release tag is [here](https://github.com/pulumi/pulumi-azure-native/releases/tag/v2.0.0-alpha.1) and the active branch is [here](https://github.com/pulumi/pulumi-azure-native/tree/v2.0-pre). There will be additional pre-releases created over the next few weeks prior to the final v2 version.

## work items

- [x] figure out how to get azure native v2 into the registry package build process
- [ ] ~hide azure native v2 from the browse page~
- [x] copy azure native content to v2 for overview and install+config
- [x] hide how-to guides tab for azure natvie v2
- [x] add preview information to card for azure native v2
- [ ] update azure native v2 overview with preview information, content to be provided by @mnlumi

**Comment by mnlumi** [comment]
Suggested text:

"v2 Preview" in page title/header.

Page title:
<img width="370" alt="Screenshot 2023-05-26 at 4 51 53 PM" src="https://github.com/pulumi/registry/assets/118926824/f1716585-430c-47a9-880e-4ab050bf9b71">

Box: 
<img width="367" alt="Screenshot 2023-05-26 at 4 55 13 PM" src="https://github.com/pulumi/registry/assets/118926824/029a94cb-66de-407c-bccc-30d2fd855698">


'Azure Native v2 is currently available in preview status. For the fully supported version, please use [Azure Native](https://www.pulumi.com/registry/packages/azure-native/). '

Also - I'd like to have the box have a different color background to draw more attention that is a preview and is clearly differentiated from the regular Azure Native docs. Let me know if this is doable.

**Comment by susanev** [comment]
@mnlumi id recommend against turning the box a different color, but we can add a background color to the notes; can you also write text for the overview page?
