### ISSUE TITLE
[Epic] Property rendering issues in the API docs

### ISSUE THREAD

**Issue by cnunciato** [pulumi/registry#3906]
This issue tracks open issues around the rendering and linking of input and output properties in the API docs.

```[tasklist]
### Tasks
- [ ] https://github.com/pulumi/pulumi/issues/12765
- [ ] https://github.com/pulumi/registry/issues/3909
- [ ] https://github.com/pulumi/registry/issues/3912
- [ ] https://github.com/pulumi/registry/issues/2966
- [ ] https://github.com/pulumi/registry/issues/1442
- [ ] https://github.com/pulumi/registry/issues/3724
- [ ] https://github.com/pulumi/pulumi-terraform-bridge/issues/1693
```
