### ISSUE TITLE
Registry search - check for full name matching + update synonyms or meta descriptions

### ISSUE THREAD

**Issue by kimberleyamackenzie** [pulumi/registry#762]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details
The ideal behavior for search is that searching the name of a provider returns its package overview page at the top of the result set.  However, there is a challenge when titles on the page don't necessarily match the search terms folks might be using.  

A good example of this is https://www.pulumi.com/registry/packages/azuread/.  If I search "AzureAD", the landing page is the first result.  However, if I search "Azure active directory," the overview doesn't make it into the first page of results, because we don't use that full name in the tags or title. 

We should:

- [ ] Do a pass to see what existing packages this is an issue for
- [ ] Either update the meta descriptions of these packages to include the full name, or create synonyms in swiftype (so searching "azure active directory" searches "azuread" too).
- [ ] Document some best practice here for new packages so this doesn't require manual intervention going forward
